### ISSUE TITLE
跪求解答

### ISSUE THREAD

**Issue by onlyaiai0516** [kingkaki/weblogic-scan#2]
C:\Users\Thinkpad>C:\Users\Thinkpad\AppData\Local\Programs\Python\Python38\python.exe C:\Users\Thinkpad\Downloads\weblogic-scan-master\weblogic-scan.py 测试域名:7001
[32m               _     _             _
 __      _____| |__ | | ___   __ _(_) ___      ___  ___ __ _ _ __
 \ \ /\ / / _ \ '_ \| |/ _ \ / _` | |/ __|____/ __|/ __/ _` | '_ \
  \ V  V /  __/ |_) | | (_) | (_| | | (_______\__ \ (__ (_| | | | |
   \_/\_/ \___|_.__/|_|\___/ \__, |_|\___|    |___/\___\__,_|_| |_|
                             |___/

github:  https://github.com/kingkaki/weblogic-scan
[32m
[33m[-] is busy: 7001:80[33m

请问这个是什么意思？

**Comment by kingkaki** [comment]
从代码上来说就是
```python
except requests.exceptions.ConnectionError as e:
		info("[-] is busy: {}".format(target))
```
也就是说requests连接失败，端口不可访问吧

**Comment by kingkaki** [comment]
有点奇怪的是这里怎么多了个80端口，感觉可能是域名格式的问题，解析的时候自动多了个:80

**Comment by onlyaiai0516** [comment]
C:\Users\Thinkpad\AppData\Local\Programs\Python\Python38\python.exe E:\学习资料库\渗透工具包\漏洞盲扫\weblogic-scan-master\weblogic-scan-master\weblogic-scan.py 192.168.32.133:7001 我是直接执行的啊。好像确实冒出来个80端口 求解

**Comment by kingkaki** [comment]
我这边显示的是没问题的，暂时无法复现，检查下符号是不是英文之类的吧
![](https://raw.githubusercontent.com/kingkaki/cloud-img/master/img/20200119172817.png)
